### ISSUE TITLE
LOADIN, STOREIN not working as documented

### ISSUE THREAD

**Issue by bewies** [hiwye/reti-emulator#1]
## LOADIN and STOREIN need some maintanance

1. The cryptic line

> LOADIN and STOREIN are used as follows: LOADIN ACC IN1

does not tell anything about how the command is used.
Rather the command ```LOADIN1 i``` from the ReTI-lecture now becomes ```LOADIN 1 i```.

2. These commands have an error in their implementation:

  It should say:
  
  > acc = s[ind[j] + i]  
  
  But it says:
  > acc = s[ind[j], i]

This fix would be nice, as this code is used for university practice tasks.

**Comment by sebwalk** [comment]
Feel free to submit PRs fixing these issues - I'm happy to merge it!
